# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: Home Background Section
  description: Home Background Section
  icon: "cottage"

# Defines the structure of this component, as well as the default values
blueprint:
  background: /images/hero/background.jpg

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  background:
    comment: Enter a section background
    type: image

