# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: Home Hero Section
  description: Home Hero Section
  icon: "cottage"

# Defines the structure of this component, as well as the default values
blueprint:
  title: Email Marketing is Future for Grow Your Business Revenues

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  background:
    comment: Background of section
    type: image
  title:
    comment: Enter a section title
    type: string
  subtitle:
    comment: Enter a section subtitle
    type: string
  image:
    type: image
  image_alt:
    type: string
  button.label:
    type: string
  button.link:
    type: url
