# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: Home Hero Section
  description: Home Hero Section
  icon: "cottage"

# Defines the structure of this component, as well as the default values
blueprint:
  title: Welcome to
  subtitle: The Beauty Nail Art.
  image: /images/home/home_hero_bg.png
  image_alt: Hero image

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  title: Enter a section title
    type: text
  subtitle: Enter a section subtitle
    type: text
  image: Background of section
    type: image
  image_alt: 
    type: text
