# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: A Section
  description: A Section
  icon: "cottage"

# Defines the structure of this component, as well as the default values
blueprint:
  title: Email Marketing is Future for Grow Your Business Revenues


# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  title:
    label: Title
    comment: Enter a section title
    type: String
  # slider[*]:
  #   image:
  #     type: image
  #   image_alt:
  #     type: string
  #   author:
  #     type: string
  #   designation:
  #     type: string
  #   message:
  #     type: string

