# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: About Section
  description: About Section
  icon: "cottage"

# Defines the structure of this component, as well as the default values
blueprint:
  title: About Us
  subtitle: Come to visit our nail salon and enjoy the comfortable relaxing moments by the leading service provided. At I-Spa Lash Nails Lounge, you are able to immerse into a cozy and luxurious space, reduce your stress of work, and forget all life’s pressure. Our valued customers will be satisfied with all services by our friendly, passionate staff. We always try our best to upgrade all services and give you the best moment.
  image: /images/home/about.png
  image_alt: 
  button: 
    url: /
    text: More


# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  title: Enter a section title
    type: text
  subtitle: Enter a section subtitle
    type: text
  image: Iamge of section
    type: image
  image_alt: 
    type: text
  button.url:
    type: text 
  button.text: 
    type: text
