# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: Massage Section
  description: Massage Section
  icon: "cottage"

# Defines the structure of this component, as well as the default values
blueprint:
  title: Massage
  subtitle: Our staff always works with their talent and passion. You would be treated carefully and thoroughly at any time.

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  title: Enter a section title
    type: string
  subtitle: Enter a section subtitle
    type: string
  image: 
    type: image
  image_alt:
    type: string

