# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: Nails Special Section
  description: Nails Special Section
  icon: "cottage"

# Defines the structure of this component, as well as the default values
blueprint:
  title: Nails Special
  subtitle: Nails Salon & Spa is always up-to-date with the latest technology and trends in the nail industry. With years of experience, we take pride in doing a great job.
  image: /images/home/nails-special.png
  image_alt: 

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  title: Enter a section title
    type: string
  subtitle: Enter a section subtitle
    type: string
  image: Iamge of section
    type: image
  image_alt: 
    type: string
