# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: Video Section
  description: Video Section
  icon: "cottage"

# Defines the structure of this component, as well as the default values
blueprint:
  title: Video
  image: /images/video/video-thumb.jpg
  image_alt: Video alt
  video_url: https://vimeo.com/45830194

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  title:
    comment: Enter a section title
    type: string
  image:
    type: image
  image_alt:
    type: string
  video_url:
    type: string

